### ISSUE TITLE
foreach 內容建議拆分成獨立子函式

### ISSUE THREAD

**Issue by flamerecca** [slps970093/Laravel-SystemMonitor#2]
foreach 裡面東西太多，建議拆成獨立子函式說明其用途

https://github.com/slps970093/Laravel-SystemMonitor/blob/9d9b8e9769142092f87a0cea9fb510f4ad3c5be5/src/Monitor/Disk/DiskFreeMonitor.php#L35

**Comment by slps970093** [comment]
拆出去了 感謝建議 XDDD
